agent:
  id: "windows-agent-001"
  name: "Windows Security Agent"
  version: "1.0.0"
  collector_interval: 30
  log_level: "info"

database:
  host: ""
  port: 
  user: ""
  password: ""
  dbname: "endpoint_security"
  sslmode: "disable"

server:
  port: 8080
